version: '3'
services:
  app:
    image: 0xcaafe/cafe
    environment:
    - PORT=${PORT}
    - HOST=${HOST}
    - NODE_ENV=${NODE_ENV}
    - APP_KEY=${APP_KEY}
    - DRIVE_DISK=${DRIVE_DISK}
    - SESSION_DRIVER=${SESSION_DRIVER}
    - CACHE_VIEWS=${CACHE_VIEWS}
    - DB_CONNECTION=${DB_CONNECTION}
    - PG_HOST=${PG_HOST}
    - PG_PORT=${PG_PORT}
    - PG_USER=${PG_USER}
    - PG_PASSWORD=${PG_PASSWORD}
    - PG_DB_NAME=${PG_DB_NAME}
    - VT_KEY=${VT_KEY}
    - ABUSEIPDB_KEY=${ABUSEIPDB_KEY}
    - OTX_KEY=${OTX_KEY}
    ports:
      - "8080:1337"